[tool.poetry]
name = "rclone-lambda-sync"
version = "1.2.0"  # Same version in package.json and serverless.yaml
description = ""
authors = ["Ayaz Badouraly <badouralix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "~3.9"
python-json-logger = "^2.0.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
boto3 = "^1.20.46"
boto3-stubs = {extras = ["ssm"], version = "^1.20.46"}
ddtrace = "^0.57.3"
flake8 = "^4.0.1"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
