[tool.poetry]
name = "rclone-lambda-sync"
version = "1.0.0"  # Same version in package.json and serverless.yml
description = ""
authors = ["Ayaz Badouraly <badouralix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "~3.8"
python-json-logger = "^2.0.1"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
boto3 = "^1.17.73"
boto3-stubs = {extras = ["ssm"], version = "^1.17.73"}
ddtrace = "^0.48.3"
flake8 = "^3.9.2"
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
