[tool.poetry]
name = "rclone-lambda-sync"
version = "2.0.0"  # Same version in package.json
description = ""
authors = ["Ayaz Badouraly <badouralix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "~3.9"
python-json-logger = "^2.0.4"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
boto3 = "^1.24.51"
boto3-stubs = {extras = ["ssm"], version = "^1.24.51"}
ddtrace = "^1.3.2"
flake8 = "^5.0.4"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
